### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by ghost** [fgeyer/openpilight#1]
root@raspberrypi:~/openpilight/openpilight# make
g++ -Wall -Ofast -mfpu=vfp -mfloat-abi=hard -march=armv6 -mtune=arm1176jzf-s -I/usr/local/include -L/usr/local/lib -lrf24-wpi -lwiringPi -c src/UDPServer.cpp -o obj/UDPServer.o
src/UDPServer.cpp: In constructor ‘UDPServer::UDPServer(const string&, int)’:
src/UDPServer.cpp:60:62: error: ‘snprintf’ was not declared in this scope
src/UDPServer.cpp: In member function ‘int UDPServer::timed_recv(char_, size_t, int)’:
src/UDPServer.cpp:212:5: error: ‘errno’ was not declared in this scope
src/UDPServer.cpp:212:13: error: ‘EAGAIN’ was not declared in this scope
Makefile:14: recipe for target 'obj/UDPServer.o' failed
make: *_\* [obj/UDPServer.o] Error 1

Any idea? Running on Raspian Wheezy / B+-Modell

**Comment by PlumIsNoGeek** [comment]
You could try to add -std=gnu++11 to the Makefile C++ Parameters... Feedback would be appreciated.
